### ISSUE TITLE
Script

### ISSUE THREAD

**Issue by Nine0512** [win2114/OurTeam#12]
สคริป

**Comment by win2114** [comment]
หลายวันที่ผ่านมาเขารู้สึกดวงไม่ดีทำอะไรก็พลาดไปหมดเลยไปให้หมอดูตรวจสอบเรื่องความโชคร้ายด้วยไพ่ยิปซีว่าเรื่องที่เกิดขึ้นรอบตัวว่าเกิดอะไรขึ้นทำไมถึงโชคร้ายพอไปถึงหมอดูถามว่ามาดูเรื่องอะไร เขาตอบไปว่าเรื่องโชคครับ หมอดูเริ่มถาม คุณชื่ออะไร ผมชื่อ ต๋อย เกิดวันที่เท่าไหร่ ผมบอกไป 18 เดือน มิถุนายน พ.ศ.2511 พอหมอดูตรวจโชคชะตา ให้จากไพ่ยิปซีของเขาเเล้วเขาบอกว่า ให้เลิกสุราเพราะอาจไปพูดหลบหลู่สิ่งศักดิ์สิทธิ์เอาไว้เลยทำให้ดวงช่วงนี้มีเเต่ความโชคร้าย หลังจากขอบคุณหมอดูเสร็จ ผมก็กลับบ้านเเล้ววันรุ่งขึ้นก็ไปทำบุญขอขมาขอโทษสิ่งที่ทำพลาดไป หลังจากเหตุการณ์ครั้งนี้ ความโชคร้ายก็หายไป
1.นาย ต๋อย
2.ดูดวงเรื่อง ความโชคร้าย
3.06/09/2511
4.ไม่เคยดูมาก่อน
5.ดูไพ่ยิปซี
6.หลังจากเหตุการณ์ครั้งนั้น ความโชคร้ายก็หายไป

**Comment by w-worw** [comment]
1.สร้างแอปนี้มาทำไม

**Comment by w-worw** [comment]
2.แอปนี้ช่วยอะไรได้บ้าง

**Comment by Nine0512** [comment]
1: สร้างเพราะในช่วง covid-19 ออกไปหาหมอดูลำบากหรือในเวลาปกติก็มีการจราจรที่ติดขัดลำบากในการเดินทางเลยสร้างแอปนี้ขึ้นมา

**Comment by w-worw** [comment]
3.แอปนี้มีดียังไง

**Comment by Matanun** [comment]
3:ประหยัด และสามารถดูดวงได้หลากหลายรูปแบบ

**Comment by khetsopon3aut** [comment]
2.คำทำนายมีความตรงเหมือนการไปดูหมอโดยตรง และทำให้คนเข้าถึงการดูดวงได้ง่ายยิ่งขึ้น

**Comment by w-worw** [comment]
สวยยยย
