### ISSUE TITLE
Story Board

### ISSUE THREAD

**Issue by w-worw** [win2114/OurTeam#15]
Story board

**Comment by Nine0512** [comment]
![Screenshot 2021-11-13 142244](https://user-images.githubusercontent.com/88127348/141610029-06feb2ea-022d-4082-9ddf-d2a99aba840a.jpg)
]

**Comment by w-worw** [comment]
![image](https://user-images.githubusercontent.com/88101493/141610046-2d9d1012-48a4-4235-8559-a96da82f11b3.png)

**Comment by Matanun** [comment]
![image](https://user-images.githubusercontent.com/88131091/141610072-518dc32b-dad3-4bd8-a673-489528faf9b4.png)

**Comment by w-worw** [comment]
![image](https://user-images.githubusercontent.com/88101493/141610099-de52ebec-3934-450d-b39b-a5cdcfabf2f2.png)

**Comment by Nine0512** [comment]
![Screenshot 2021-11-13 142658](https://user-images.githubusercontent.com/88127348/141610118-784d4396-5cd3-4655-95ce-ca09a6d293ad.jpg)

**Comment by w-worw** [comment]
niceee
