### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by w-worw** [win2114/OurTeam#16]
https://www.figma.com/proto/4inD4884AfmPOkIZ0MEUtd/Untitled?node-id=1%3A400&scaling=scale-down&page-id=0%3A1&starting-point-node-id=3%3A18

เอาไปลองให้คนอื่นๆใช้แล้วขอ feedback หน่อย

**Comment by Nine0512** [comment]
ตัวแอปโอเคดูใช้ง่ายแต่อยากให้เพิ่ม
1.แหล่งที่มาของการหลักการในการดูดวงว่ามาจากไหนน่าเชื่อถือไหม
2.การคุยกับหมอดูแบบตัวต่อตัว
3. ถ้าห้แอปสวยกว่าจะดูใช้ง่ายเข้าไปอีก

**Comment by Matanun** [comment]
1.แอปดูยังไม่ค่อยสวยงาม
2.ตัวแอปใช้งานง่าย
3.ระบบต่างๆดูน้อยไปหน่อย

**Comment by khetsopon3aut** [comment]
แอปสามารถเข้าถึงได้ง่าย และผู้พูดอธิบายหลักการทำของแอปได้อย่างชัดเจนแต่ขอเพิ่ม
1.การออกแบบสวยแล้วแต่อยากให้ตกแต่งมากกว่านี้
2.อยากให้เพิ่มวิธีการทำนายเช่น ตัวเลขมงคล สีนำโชคแต่ละวันเป็นต้น
3.สถานที่ของหมอดูเผื่อกรณีอยากไปดูโดยตรง

**Comment by w-worw** [comment]
ตัวแอปดูใช้ง่ายแต่รายละเอียดกับความสวยงามดูน้อยไปหน่อย

**Comment by Soraiwt01** [comment]
1.การออกแบบสวยแล้วแต่อยากให้เพิ่มการตกแต่งมากกว่านี้ว่านี้มันดูพื้นที่เหลือมากเกินไป
2.อยากให้เพิ่มช่องทางการติดต่อของหมอดูเผื่อกรณีอยากไปดูโดยตรง
3.อยากให้เพิ่มลุกเล่นการทำนายในเเอปเช่น วงล้อเสี่ยงโชค ของนำโชค เป็นของแต่ละวันไป

**Comment by Pupha2546** [comment]
1.อยากให้มีรายละเอียดในแต่ละหน้าเยอะขึ้น
2.อยากให้มีส่วนของ menu เพิ่มมาเพื่อให้ง่ายต่อการใช้งาน
3.ถ้ามีช่องแชทเพื่อคุยกับหมอดูโดยตรง
