### ISSUE TITLE
interview script

### ISSUE THREAD

**Issue by w-worw** [win2114/OurTeam#2]
สัมภาษณ์เรื่องอะไรบ้าง

**Comment by win2114** [comment]
ดูดวง
1.ชื่อ จิรายุ
2.เรื่อง การเงิน
3.05/10/2545
4.ไม่เคยดู
5.-
6.-

**Comment by Nine0512** [comment]
1.นายสมปอง บุณใหญ่
2.ดูดวงเรื่องการเงิน
3. 06/12/2542
4.ดูดวงล่าสุดเดือนที่แล้ว
5.ดูไพ่ทาโร่
6.หมอดูทักว่าการเงินดีแต่ต้องระวังว่าจะมีรางต้องใช้เงินก้อนโตกระทันหัน

**Comment by win2114** [comment]
จิรายุเป็นคนที่เงียบเหงาแล้วเค้ารู้สึกว่าอยากหาใครสักคนมาอยู่ด้วยกันเค้าเลยอยากไปดูดวง เพื่อนของเขาจึงแนะนำมาว่าให้ไปดูดวงกับหมอดู ร้านแถวประชาอุทิศ จิรายุจึงรับข้อเสนอแล้วเดินทางไป เมื่อถึงหมอดูทักจิรายุว่าเราเนี่ยดู เหงาหงอยนะไม่มีแฟนหรอ จิรายุเลยตอบว่าใช่ หมอดูเลยถามวันนี้จะมาดูเรื่องความรักใช่ไหม จิรายุตอบว่าใช่
1.นาย จิรายุ
2.ดูดวงเรื่องความรัก
3.05/10/2540
4.ไม่เคยดูมาก่อน
5.-
6.-

**Comment by Soraiwt01** [comment]
หลายวันที่ผ่านมารู้สึกดวงไม่ดีทำอะไรก็พลาดไปหมดเลยไปให้หมอดูตรวจสอบเรื่องความโชคร้ายด้วยไพ่ยิปซีว่าเรื่องที่เกิดขึ้นรอบตัวว่าเกิดอะไรขึ้นทำไมถึงโชคร้ายพอไปถึงหมอดูถามว่ามาดูเรื่องอะไร ผมตอบไปว่าเรื่องโชคครับ หมอดูเริ่มถาม คุณชื่ออะไร ผมชื่อ ต๋อย เกิดวันที่เท่าไหร่ ผมบอกไป 18 เดือน มิถุนายน พ.ศ.2511 พอหมอดูตรวจโชคชะตา ให้จากไพ่ยิปซีของเขาเเล้วเขาบอกว่า ให้เลิกสุราเพราะอาจไปพูดหลบหลู่สิ่งศักดิ์สิทธิ์เอาไว้เลยทำให้ดวงช่วงนี้มีเเต่ความโชคร้าย หลังจากขอบคุณหมอดุเสร็จ ผมก็กลับบ้านเเล้ววันรุ่งขึ้นก็ไปทำบุญขอขมาขอโทษสิ่งที่ทำพลาดไป หลังจากเหตุการณ์ครั้งนี้ ความโชคร้ายก็หายไป
1.นาย ต๋อย
2.ดูดวงเรื่อง ความโชคร้าย
3.06/09/2556
4.ไม่เคยดูมาก่อน
5.ดูไพ่ยิปซี
6.หลังจากเหตุการณ์ครั้งนั้น ความโชคร้ายก็หายไป

**Comment by Matanun** [comment]
อยากไปดูเรื่องการงานเพราะกำลังจะเปิดธุรกิจใหม่ เคยไปดูดวงมาแล้วที่นึงเมื่อนานมาแล้ว หมอดูทักว่าการงานจะไม่ราบลื่น ขัดสน ทำสิ่งไหนก็ไม่สำเร็จ หมอดูได้แนะนำให้ไปทำบุญ ตอนนี้เลยอยากจะดูดวงตอนนี้ใหม่ว่าดวงชะตาจะดีขึ้นไหม
1.ชื่อนายแดง แด๊งแดง  
2.ดูดวงเรื่องการงาน  
3.05/2/2541 
4.เคยดูเมื่อ 5 เดือนที่แล้ว 
5.เคยดูลายมือ  
6.หมอดูทักว่าทำงานอะไรก็ขัดสน ไม่เป็นไปดั่งใจ มีแต่ความโชคร้าย

**Comment by khetsopon3aut** [comment]
แยมนัดจองคิวหมอดูตอนบ่ายตอนเดินทางมาถึงต้องรอคิวก่อนหน้าประมาณ15นาที สาเหตุที่มาดูดวงเนื่องจากตนสมัครงานใหม่ไปหลายที่แต่ยังไม่มีใครตอบกลับพอถึงคิวหมอจึงเริ่มถามถึงวันเกิดของแยมหลังจากนั้นจึงให้ถามคำถามแยมจึงถามถึงเรื่องงานในอนาคตว่าตนเองได้งานที่มั่นคง  และประสบความสำเร็จไหม โดยสาเหตุที่มาดูหมอดูคนนี้เนื่องจากได้รับคำแนะนำมาจากแม่ของตนว่าหมอดูคนที่ดูดวงแม่นมาก ซึ่งปกติแยมไม่ค่อยได้ดูดวงซักเท่าไหร่ ครั้งล่าสุดเมื่อประมาณ1ปีที่แล้ว หลังจากถามเสร็จหมอดูก็ได้ให้แยมเลือกไพ่มาประมาณ7ใบ แล้วจึงทำนายว่าในอนาคตแยมจะประสบความสำเร็จและมีการงานที่มั่นคงแต่ให้ระวังเรื่องคนในที่ทำงานเนื่องจากบางคนจะไม่ชอบหน้าแยม
1. แยม
2. ดูดวงเรื่องงาน
3. 31/5/2539
4. 1ปีที่แล้ว
5. ใช้ไพ่ยิปซี
6. จะประสบความสำเร็จแต่ให้ระวังเรื่องเพื่อนร่วมงาน

**Comment by Pupha2546** [comment]
สัมภาษณ์ : น้าพลอย 
การดูดวงครั้งล่าสุด : เนื่องจากสถานการณ์โควิด จึงเลือกที่จะดูดวงผ่านทาง Live สด แต่เนื่องจากต้องรอคิดแต่ก็มาไม่ถึงซักทีเลยทำให้ต้องผ่านไป 2 วันโดยมาต่อคิวทุกวันแล้วก็มาได้ตอนวันที่สามโชคดีมาก ซึ่งเรื่องที่ดูก็คือเรื่องความรัก หมอดูถามถึงชื่อวันเดือนที่เกิด แล้วก็ให้อธิษฐาน แล้วหมอดูก็เปิดไพ่ทีละไปแล้วที่จำได้หมอบอกว่า 1.ช่วงนี้อาจจะมีคนเข้ามา 2.เป็นคนที่ดูมีภูมิฐาน 3.แต่จะมากับบททดสอบ  อย่าทำอะไรวู่วาม ถ้าผ่านไปได้คุณจะได้คู่แท้
1.นาง พลอย
2.ดูดวงเรื่อง ความรัก
3.09/05/2536
4.เมื่อ 2 เดือนที่แล้ว
5.ดูไพ่ยิปซี
6.ตอนนี้กำคบหาดูใจกับหนุ่มคนนั้นอยู่

**Comment by w-worw** [comment]
ที่นี่คิดได้คือทำไมถึงอยากไปดูดวงอะ

**Comment by Soraiwt01** [comment]
เรื่อง โชค โชคดี โชคร้าย

**Comment by Matanun** [comment]
ความรัก

**Comment by Pupha2546** [comment]
ความรัก

**Comment by khetsopon3aut** [comment]
การงาน

**Comment by Nine0512** [comment]
การเงิน การงาน

**Comment by w-worw** [comment]
1.ชื่ออะไร
2.ดูเรื่องอะไร

**Comment by Pupha2546** [comment]
หมอดูแบบไหน

**Comment by Nine0512** [comment]
ผลออกมาเป็นยังไง

**Comment by Matanun** [comment]
เคยดูมาก่อนไหม

**Comment by Nine0512** [comment]
ดูล่าสุดเมื่อไหร่

**Comment by khetsopon3aut** [comment]
สาเหตุที่ไปดูดวง

**Comment by w-worw** [comment]
1.ชื่ออะไร
2.ดูเรื่องอะไร
3.สาเหตุที่ไปดู
4.หมอดูแบบไหน
5.ดูล่าสุดเมื่อไร
6.ผลเป็นยังไง
แล้วดูกับหมอดูคนที่พึ่งไปดูมาเป็นยังไง

**Comment by w-worw** [comment]
ประมาณนี้นะ

**Comment by Nine0512** [comment]
ok

**Comment by Matanun** [comment]
โอเค

**Comment by Soraiwt01** [comment]
ok

**Comment by w-worw** [comment]
เคงั้นไปทำresultต่อนะ
