### ISSUE TITLE
what-how-why

### ISSUE THREAD

**Issue by w-worw** [win2114/OurTeam#4]
What how why ของต้า

**Comment by w-worw** [comment]
หลายวันที่ผ่านมาเขารู้สึกดวงไม่ดีทำอะไรก็พลาดไปหมดเลยไปให้หมอดูตรวจสอบเรื่องความโชคร้ายด้วยไพ่ยิปซีว่าเรื่องที่เกิดขึ้นรอบตัวว่าเกิดอะไรขึ้นทำไมถึงโชคร้ายพอไปถึงหมอดูถามว่ามาดูเรื่องอะไร เขาตอบไปว่าเรื่องโชคครับ หมอดูเริ่มถาม คุณชื่ออะไร ผมชื่อ ต๋อย เกิดวันที่เท่าไหร่ ผมบอกไป 18 เดือน มิถุนายน พ.ศ.2511 พอหมอดูตรวจโชคชะตา ให้จากไพ่ยิปซีของเขาเเล้วเขาบอกว่า ให้เลิกสุราเพราะอาจไปพูดหลบหลู่สิ่งศักดิ์สิทธิ์เอาไว้เลยทำให้ดวงช่วงนี้มีเเต่ความโชคร้าย หลังจากขอบคุณหมอดุเสร็จ ผมก็กลับบ้านเเล้ววันรุ่งขึ้นก็ไปทำบุญขอขมาขอโทษสิ่งที่ทำพลาดไป หลังจากเหตุการณ์ครั้งนี้ ความโชคร้ายก็หายไป
1.นาย ต๋อย
2.ดูดวงเรื่อง ความโชคร้าย
3.18/06/2511
4.ไม่เคยดูมาก่อน
5.ดูไพ่ยิปซี
6.หลังจากเหตุการณ์ครั้งนั้น ความโชคร้ายก็หายไป

**Comment by w-worw** [comment]
what : รู้สึกว่าดวงไม่ดีแล้วรู้สึกอยากไปดูดวง

**Comment by Nine0512** [comment]
what : รู้สึกดวงไม่ดี

**Comment by Soraiwt01** [comment]
what : มีเหตุการณ์ความโชคร้ายเกิดขึ้นบ่อยครั้งในช่วงเวลานี้

**Comment by win2114** [comment]
แล้วรู้สึกอยากไปดูดวง

**Comment by Soraiwt01** [comment]
why : หมอดูมีความน่าเชื่อถือ มีคนมาคอมเมนต์มากมาย

**Comment by Pupha2546** [comment]
what : อยากไปดูหมอเรื่องความโชคร้าย
how : ไปหาหมอดู
why : ช่วงนี้เจอแต่เรื่องไม่ดี

**Comment by w-worw** [comment]
How : หาจากที่เรตติ้งดีๆ

**Comment by Nine0512** [comment]
How : มีคนพูดถึงเยอะ

**Comment by Matanun** [comment]
why : อยากมีแต่ความโชคดี

**Comment by khetsopon3aut** [comment]
why: อยากรู้ว่าทำไมตนถึงโชคร้าย

**Comment by Pupha2546** [comment]
what : อยากให้เรื่องร้ายๆหมดไป
how : ไปทำบุญ

**Comment by Nine0512** [comment]
What
อยากไปดูหมอเรื่องความโชคร้าย
มีเหตุการณ์ความโชคร้ายเกิดขึ้นบ่อยครั้งในช่วงเวลานี้
รู้สึกดวงไม่ดี
รู้สึกว่าดวงไม่ดีแล้วรู้สึกอยากไปดูดวง
อยากให้เรื่องร้ายๆหมดไป

How
ไปหาหมอดู
หาจากที่เรตติ้งดีๆ
มีคนพูดถึงเยอะ
ไปทำบุญ

Why
อยากมีแต่ความโชคดี
อยากรู้ว่าทำไมตนถึงโชคร้าย
ช่วงนี้เจอแต่เรื่องไม่ดี
หมอดูมีความน่าเชื่อถือ มีคนมาคอมเมนต์มากมาย

**Comment by w-worw** [comment]
โอเคงั้นไปทำuser personaต่อนะ
