### ISSUE TITLE
user persona

### ISSUE THREAD

**Issue by w-worw** [win2114/OurTeam#5]

**Comment by Soraiwt01** [comment]
![image](https://user-images.githubusercontent.com/88130132/139539578-eeeaeeff-ac9c-4faa-ae46-9c1b5316d815.png)

**Comment by win2114** [comment]
สวยยย

**Comment by Nine0512** [comment]
![Ivory Black Simple Professional Digital Marketer Resume](https://user-images.githubusercontent.com/88127348/139539593-0d9b5892-e6c3-4915-87b7-a90f598d36d6.jpg)

**Comment by w-worw** [comment]
สวยยย

**Comment by w-worw** [comment]
ไปทำ journey map ต่อนะ
