### ISSUE TITLE
journey map

### ISSUE THREAD

**Issue by w-worw** [win2114/OurTeam#6]

**Comment by w-worw** [comment]
![Copy of INT100-DT-worksheet G2-5](https://user-images.githubusercontent.com/88101493/139540495-a39751e2-5dcd-4499-9ee7-5ad0bd38f0cb.png)

**Comment by Soraiwt01** [comment]
ok เลย

**Comment by Nine0512** [comment]
สวย

**Comment by w-worw** [comment]
โอเคงั้นไปทำPoVต่อนะ

**Comment by khetsopon3aut** [comment]
ได้ๆ
