### ISSUE TITLE
PoV

### ISSUE THREAD

**Issue by w-worw** [win2114/OurTeam#7]
1. We met : 
2. We were surprised to notice : 
3. We wonder if this mean : 
4. It would be game-changing to :

**Comment by Soraiwt01** [comment]
1.ดวงไม่ดีเลยไปหาหมอดู

**Comment by w-worw** [comment]
2.เป็นการเดินทางที่ไกลมากทำให้เซ็งหน่อยๆ

**Comment by w-worw** [comment]
3.ไม่อยากเดินทางไกลและสามารถคุยกับหมอดูคนนี้ได้

**Comment by Nine0512** [comment]
4.หาทางที่จะไม่เดินทางไกลเพื่อไปหาหมอดู

**Comment by Matanun** [comment]
1.ดวงไม่ดีเลยไปหาหมอดู
2.เป็นการเดินทางที่ไกลมากทำให้เซ็งหน่อยๆ
3.ไม่อยากเดินทางไกลและสามารถคุยกับหมอดูคนนี้ได้
4.หาทางที่จะไม่เดินทางไกลเพื่อไปหาหมอดู
